import type { GetKnownSkin } from './types';
export declare const palette: {
    movistarBlue: string;
    movistarBlue10: string;
    movistarBlue20: string;
    movistarBlue30: string;
    movistarBlue40: string;
    movistarBlue55: string;
    movistarGreen: string;
    movistarGreen10: string;
    movistarGreen30: string;
    movistarGreen40: string;
    movistarGreen60: string;
    movistarGreen70: string;
    pepper: string;
    pepper10: string;
    pepper40: string;
    pepper55: string;
    pepper70: string;
    egg: string;
    egg10: string;
    egg40: string;
    egg80: string;
    pink: string;
    purple: string;
    purple10: string;
    purple40: string;
    purple70: string;
    grey1: string;
    grey2: string;
    grey3: string;
    grey4: string;
    grey5: string;
    grey6: string;
    white: string;
    movistarBlueDark: string;
    darkModeBlack: string;
    darkModeGrey: string;
    darkModeGrey2: string;
    darkModeGrey3: string;
    darkModeGrey4: string;
    darkModeGrey5: string;
    darkModeGrey6: string;
};
export declare const getMovistarSkin: GetKnownSkin;
